name: py35
channels:
  - conda-forge
  - defaults
dependencies:
  - bqplot
  - ca-certificates
  - certifi
  - openssl
  - traittypes
  - appnope
  - backcall
  - bleach
  - cycler
  - dbus
  - decorator
  - entrypoints
  - expat
  - freetype
  - gettext
  - glib
  - html5lib
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libpng
  - libsodium
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - numpy-base
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - simplegeneric
  - sip
  - six
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zlib

